http:
  routers:
    hass:
      rule: "Host(`hass`, `hass.home.arpa`, `hass.svc.home.arpa`)"
      service: hass
      entryPoints: ["web"]

    sonarr:
      rule: "Host(`sonarr`, `sonarr.home.arpa`, `sonarr.svc.home.arpa`)"
      service: sonarr
      entryPoints: ["web"]

    radarr:
      rule: "Host(`radarr`, `radarr.home.arpa`, `radarr.svc.home.arpa`)"
      service: radarr
      entryPoints: ["web"]

    plex:
      rule: "Host(`plex`, `plex.home.arpa`, `plex.svc.home.arpa`)"
      service: plex
      entryPoints: ["web"]

    deluge:
      rule: "Host(`deluge`, `deluge.home.arpa`, `deluge.svc.home.arpa`)"
      service: deluge
      entryPoints: ["web"]

    prowlarr:
      rule: "Host(`prowlarr`, `prowlarr.home.arpa`, `prowlarr.svc.home.arpa`)"
      service: prowlarr
      entryPoints: ["web"]

    traefik-dashboard:
      rule: "Host(`traefik`, `traefik.svc.home.arpa`, `traefik.home.arpa`)"
      service: api@internal
      entryPoints: ["web"]

  services:
    hass:
      loadBalancer:
        servers:
          - url: "http://192.168.1.15:8123"

    sonarr:
      loadBalancer:
        servers:
          - url: "http://gluetun:8989"

    radarr:
      loadBalancer:
        servers:
          - url: "http://gluetun:7878"

    plex:
      loadBalancer:
        servers:
          - url: "http://192.168.1.15:32400"

    deluge:
      loadBalancer:
        servers:
          - url: "http://gluetun:8112"

    prowlarr:
      loadBalancer:
        servers:
          - url: "http://gluetun:9696"
